# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy to github-pages
on: [workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies and giotto-llm
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.8.3
        poetry config virtualenvs.in-project true
        poetry install --no-interaction --no-ansi --without optional
    - name: Git checkout and build sphinx docs
      run: |
        git config --global user.name "github-pages[bot]"
        git config --global user.email "41898281+github-pages[bot]@users.noreply.github.com"
        git fetch
        git checkout github-pages
        git checkout main
        cd docs
        poetry run make html
    - name: push to github-pages
      run: |
        git symbolic-ref HEAD refs/heads/gh-pages
        git reset --mixed gh-pages
        git add --all
        git add -f docs/build
        git commit -m "push sphinx build"
        git push origin github-pages
